version: "3"

services:
  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: flask-mysql
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=flask
      - MYSQL_USER=flask
      - MYSQL_PASSWORD=flask
    ports:
      - "8003:3306"