FROM python:3.9.5-slim-buster

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt

#RUN chown -R admin:admin /app
#RUN chmod 777 /app
#USER admin
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]