# Generated by Django 3.2.5 on 2021-08-10 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0006_alter_dealer_user'),
        ('car', '0002_auto_20210803_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='population_type',
        ),
        migrations.AddField(
            model_name='car',
            name='pollutant_class',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('A+', 'A+'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='A', max_length=55),
        ),
        migrations.AlterField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='dealer.dealer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.CharField(blank=True, choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Rotary', 'Rotary'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], default='Gasoline', max_length=55),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('Gasoline', 'Gasoline'), ('Gasoline/Gas', 'Gasoline/Gas'), ('Hybrid', 'Hybrid'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], default='Gasoline', max_length=55),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear_case',
            field=models.CharField(blank=True, choices=[('Automatic', 'Automatic'), ('Semi-automatic', 'Semi-automatic'), ('Mechanical', 'Mechanical'), ('Robotic', 'Robotic')], default='A', max_length=55),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='car.model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Car Sell'), ('published', 'Published'), ('sold', 'Sold'), ('archived', 'Archived')], default='pending', max_length=55),
        ),
        migrations.AlterField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='car.brand'),
        ),
    ]
