# Generated by Django 3.2.5 on 2021-08-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20210810_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='pollutant_class',
            new_name='pollutant_type',
        ),
    ]
