# Generated by Django 3.2.5 on 2021-08-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20210828_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='property',
            field=models.ManyToManyField(to='car.Property'),
        ),
    ]
