version: "3"

services:

  web:
    build: ./docker/python/Dockerfile.prod
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
        - .:/usr/src/app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
