version: "3"

services:
  webserver:
    image: nginx:alpine
    container_name: flask-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    links:
      - web