version: "3"

services:

  mysql:
    image: mysql:8.0
    container_name: flask-mysql
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=flask
      - MYSQL_USER=flask
      - MYSQL_PASSWORD=flask
    ports:
      - "8003:3306"


  web:
    build: ./docker/python/Dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    links:
      - mysql