version: "3"

services:

  webserver:
    image: nginx:alpine
    container_name: flask-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    links:
      - web

  web:
    build: ./docker/python
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: flask-mysql
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=flask
      - MYSQL_USER=flask
      - MYSQL_PASSWORD=flask
    ports:
      - "8003:3306"