# Generated by Django 3.2.5 on 2021-08-03 14:31

from django.db import migrations, models
import django.db.models.deletion


def create_default_country(apps, schema_editor):
    country = apps.get_model("dealer", "Country")
    country = country.objects.create(name='Ukraine', code='380')
    country.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_auto_20210803_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('code', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.RunPython(create_default_country),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dealer.country'),
        ),
    ]
